### ISSUE TITLE
Migrate publication details from ce.pdn.ac.lk

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/api.ce.pdn.ac.lk#10]
We need to add that publication information to staff pages, through the Publication API (Need a volunteer)

- [pub_JanakaA.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732654/pub_JanakaA.txt)
- [pub_SunethN.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732655/pub_SunethN.txt)
- [pub_dhammikaEl.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732656/pub_dhammikaEl.txt)
- [pub_KamalanathS.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732657/pub_KamalanathS.txt)
- [pub_ManjulaS.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732658/pub_ManjulaS.txt)
- [pub_RoshanR.txt](https://github.com/cepdnaclk/api.ce.pdn.ac.lk/files/8732659/pub_RoshanR.txt)

**Comment by gihanjayatilaka** [comment]
I think we can close this issue now.
https://github.com/cepdnaclk/publications
