### ISSUE TITLE
Author Info matching Algorithm for Publications API v1

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/api.ce.pdn.ac.lk#13]
**Publications API v1** 
There is no connection between "authors" and "author_info". This can be problematic in the long run.

**Comment by NuwanJ** [comment]
Can you explain it a little more?

As for now, 
- _authors_ list is used to print the text content (order matters)
- _author_info_ is used to link the publication with the profile pages (order doesn't matter & not used for rendering the text content)

**Comment by gihanjayatilaka** [comment]
@gihanjayatilaka start writing the matching algorithm

**Comment by gihanjayatilaka** [comment]
Can we first do this https://github.com/cepdnaclk/publications/issues/7 and see how good our current data is?

**Comment by NuwanJ** [comment]
Fixed in fec1d70
