### ISSUE TITLE
Update time

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/api.ce.pdn.ac.lk#15]
When we submit some information via a google form, it reaches the first storage location within 24hrs from the GitHub actions fetching info. However, it requires updates in more than one GitHub repo for some information to appear on all places that it should appear. The full propagation may take multiple GitHub action runs (therefore more than 1 day). We can overcome this issue by 
(1) Figuring out a good sequence to run the actions
(2) Scheduling the actions according to this sequence
(3) Invoking triggers between actions.

**Comment by NuwanJ** [comment]
For now, it is done by adjusting the times of the cron jobs with 10 min gaps. The summary can be found here. https://api.ce.pdn.ac.lk/workflows/

Better someone can prepare a dependency graph, to identify the most effective sequence to trigger the actions.
