### ISSUE TITLE
Pulication API profile URL inconsistency

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/api.ce.pdn.ac.lk#17]
https://api.ce.pdn.ac.lk/publications/v1/all/

Student profile URLs: profile_url: https://people.ce.pdn.ac.lk/students/e14/000/
Staff profile URLs: /staff/academic/roshan-ragel/

**Comment by NuwanJ** [comment]
Any suggestion?

**Comment by gihanjayatilaka** [comment]
What I meant to say was the URL for staff was incomplete (URL being returned by the API). This has been solved by now.
