### ISSUE TITLE
Issue in Pubs API

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/api.ce.pdn.ac.lk#23]
Hi, Why does this happen?
https://github.com/cepdnaclk/api.ce.pdn.ac.lk/blob/ccf2b8a17e3bc9099d0d11d8f7233af03373eb94/publications/v1/10.1109/ICIAFS.2016.7946528/index.json#L24

**Comment by NuwanJ** [comment]
https://github.com/cepdnaclk/api.ce.pdn.ac.lk/blob/a25e5a8720789c6bb0ec14659c659541bd315300/python_scripts/students.py#L141-L161

Student API was previously implemented for batches E12 and onwards, since the lack of data on older batches. I will lift this limitation since now we have the details

**Comment by NuwanJ** [comment]
Fixed with baac67dc0f8ab3492e2d1fb8b7a30f3e5480eeac
